import { InjectorToken } from '@hwy-fm/di';
export declare const HTTP_INTERCEPTORS: InjectorToken;
export declare const APPLICATION_TOKEN: InjectorToken;
export declare const APPLICATION_PLUGIN: InjectorToken;
export declare const APPLICATION_METADATA: InjectorToken;
export declare const HISTORY: InjectorToken;
export declare const MICRO_OPTIONS: InjectorToken;
export declare const APP_INITIALIZER: InjectorToken;
export declare const ROUTER_CONFIG: InjectorToken;
export declare const PLATFORM: InjectorToken;
export declare const PlatformOptions: InjectorToken;
